### PR TITLE
87 mobile fixes

### LINKED ISSUE #87: Platform testing : phone ( sunna )
#85

### PR DESCRIPTION
**Pull request by mohitgusain**
#87 

1. Width screen fixes for the mobile

### CODE REVIEW

File: public/wp-content/themes/glific/template-parts/book-demo-modal.php [hunk 1]
```diff
@@ -1,6 +1,11 @@
 <div class="modal fade module-modal bd-example-modal-lg" id="demoModal" tabindex="-1" role="dialog" aria-labelledby="demoModalTitle" aria-hidden="true">
-	<div class="modal-dialog modal-dialog-centered modal-xl w-90p w-md-717 w-xl-805 max-w-full" role="document">
+	<div class="modal-dialog modal-dialog-centered modal-xl  w-md-717 w-xl-805 max-w-full" role="document">
```
Comment (Satendra-SR) [inline public/wp-content/themes/glific/template-parts/book-demo-modal.php]:
```suggestion
	<div class="modal-dialog modal-dialog-centered modal-xl w-md-717 w-xl-805 max-w-full" role="document">
```

**Review by Satendra-SR — APPROVED** [review]
Looks good 👍
